### ISSUE TITLE
silk codec怎么弄 求大佬指点

### ISSUE THREAD

**Issue by TianMuWopsd1** [xtaw/LiteLoaderQQNT-Audio-Sender#10]
实在不会了

**Comment by Zorrok-k** [comment]
进silk_codec的仓库点release，找windows 64位版本下载放到任意位置，复制这个位置，进高级系统设置配置环境变量添加这个位置的路径，把下载的exe程序重命名为silk_codec，cmd中输入silk_codec显示silk_codec即为成功
