### ISSUE TITLE
QQ会发出两段相同语音消息

### ISSUE THREAD

**Issue by MoeSnowyFox** [xtaw/LiteLoaderQQNT-Audio-Sender#12]
在拖入mp3后,音频文件夹生成.pcm文件和.silk文件,而后.pcm文件自动被删除,但qq内发出两段相同语音QQ9.9.7-21484  LL1.0.3,  LLAPI1.4.0  本体为1.0.1 ff为(ffmpeg-N-113824-ga3ca4beeaa-win64-gpl)  silk为(silk_codec-windows-static-x64(github中最新)) 
<img width="623" alt="image" src="https://github.com/xtaw/LiteLoaderQQNT-Audio-Sender/assets/156929726/022f8942-b64d-4be4-bfe4-8eab7b76304d">

**Comment by xtaw** [comment]
试试降级到LLAPI v1.3.1.1，应该是最新版没适配，等有时间了写

**Comment by questionkiller** [comment]
我是通过插件商店安装的 切换成语音发送界面后 拖入音频文件没反应
![{71111B31-C4CB-4dfe-8359-F0FE6B0D151C}](https://github.com/xtaw/LiteLoaderQQNT-Audio-Sender/assets/10951239/bad767dc-e31a-49a3-b7e0-3d461b018e11)
