### ISSUE TITLE
【bug】qq无法转换音频后无法发出

### ISSUE THREAD

**Issue by LINKlang** [xtaw/LiteLoaderQQNT-Audio-Sender#15]
拖入mp3文件后，文件文件夹下出现了.pcm文件，但是并没有后续动作，也没有发出
qq版本：9.9.7-21484
LL版本：1.0.3
LLAPI版本：[v1.3.1.1](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-LLAPI/releases/tag/v1.3.1.1)
![image](https://github.com/xtaw/LiteLoaderQQNT-Audio-Sender/assets/116951234/8a5b1286-f8e1-49d8-902c-161ee67ca5ec)
![image](https://github.com/xtaw/LiteLoaderQQNT-Audio-Sender/assets/116951234/c24f28d8-8d7f-4d82-8ddd-0e2c5feade15)

**Comment by xtaw** [comment]
可以尝试最新版
