### ISSUE TITLE
[bug] 重复发送

### ISSUE THREAD

**Issue by yhzcake** [xtaw/LiteLoaderQQNT-Audio-Sender#17]
如题,将文件拖入后会每次发送两条语音
![image](https://github.com/xtaw/LiteLoaderQQNT-Audio-Sender/assets/80627671/a075ef3b-067e-46ae-9e45-617f5f57ced5)

**Comment by xtaw** [comment]
请给出安装的插件列表

**Comment by xtaw** [comment]
只启用audiosender和llapi的时候是否会出现这种情况

**Comment by yhzcake** [comment]
应该是[LiteLoaderQQNT-TTS](https://github.com/lclichen/LiteLoaderQQNT-TTS)一起导致的

**Comment by xtaw** [comment]
看了一下源码，那边插件应该是也带了一个发送语音的功能
`（Copy From Voice Sender）点击编辑框上方的语音图标，切换到发送语音界面，直接将音频文件拖入聊天窗口即可`

**Comment by yhzcake** [comment]
> 看了一下源码，那边插件应该是也带了一个发送语音的功能 `（Copy From Voice Sender）点击编辑框上方的语音图标，切换到发送语音界面，直接将音频文件拖入聊天窗口即可`

居然是这样吗...好离谱
