### ISSUE TITLE
没安装成功，不知道是我没搞好还是哪里出了问题，我是废物，能不能写个详细点的教程或者录个视频

### ISSUE THREAD

**Issue by boom6904** [xtaw/LiteLoaderQQNT-Audio-Sender#4]
如标题，主要是silk-codec不知道怎么装，不确定装上没，直接试也没成功，也可能是我其他哪里搞错了

**Comment by xtaw** [comment]
silk-codec那个exe记得改名为silk-codec.exe

**Comment by boom6904** [comment]
还是不行，我之前完全没接触过这个项目涉及的工具我不确定是不是我其他地方搞错了，我是先下载[FFmpeg]的压缩文件解压后讲bin文件夹添加到系统环境变量Path然后把silk_codec-windows-static-x64.exe改为silk-codec.exe放入bin文件夹然后在LiteLoaderQQNT插件商店添加LLAPI然后重启qq，在cmd里可以使用FFmpeg的指令，原本不能跨权限等级拖拽文件我去注册表按网上教程修改了一个项关闭UIPI了，这个过程有哪里有问题嘛？我之前完全没接触过这些

**Comment by boom6904** [comment]
在qqNT语音界面拖拽文件进去没反应，文件格式是mp3，关闭语音界面或者直接拖到聊天界面会放入聊天栏

**Comment by xtaw** [comment]
应该是silk_codec.exe，下划线

**Comment by boom6904** [comment]
对不起，刚刚打错了，我图方便直接复制了宁的回复里的我原本改的应该是silk_codec.exe，刚刚又试了一下silk-codec.exe cmd写
silk_codec指令都没反应又改回silk_codec.exe了还是不行

**Comment by boom6904** [comment]
用silk_codec.exe cmd指令可以用

**Comment by boom6904** [comment]
但是qqNT里没反应

**Comment by xtaw** [comment]
cmd内不带.exe能否使用

**Comment by boom6904** [comment]
silk_codec开头的指令可以用，带.exe好像也行

**Comment by xtaw** [comment]
能否发一下可以用于复现的音频文件和文件路径，以及操作系统是什么

**Comment by boom6904** [comment]
C:\Users\wk135\Music\DAOKO-_-米津玄師-打上花火.mp3，windows11专业版 23H2 22631.3007，音频文件是怎么发？

**Comment by boom6904** [comment]
好像不支持mp3

**Comment by boom6904** [comment]
FFmpeg在F:\ffmpeg-master-latest-win64-gpl-shared

**Comment by boom6904** [comment]
qqNT在"F:\Program Files\Tencent\QQNT\QQ.exe"

**Comment by boom6904** [comment]
注册表关闭UIPI删除了”计算机\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender“中较长的那项（应该没有影响怕有影响也说明一下）

**Comment by boom6904** [comment]
大佬刚刚我想着试试把系统同版本覆盖安装了一下然后qq报错打不开我修复然后重启了一下就好了

**Comment by boom6904** [comment]
谢谢大佬了麻烦了
