### ISSUE TITLE
无法使用（？）

### ISSUE THREAD

**Issue by File-saver** [xtaw/LiteLoaderQQNT-Audio-Sender#6]
![83b86fcb217bb394677eaee0d525a8d4](https://github.com/xtaw/LiteLoaderQQNT-Audio-Sender/assets/54362633/907f402c-31c9-48db-98ff-1b1e4f6a4b65)
环境变量ffmpeg和silk_codec均已配置好

拖入音频文件（.mp3，约30秒）到录音界面没有反应，在文件目录下先后生成了.pcm文件和.silk文件，然后.pcm被删除，.silk未被删除，音频没有发送成功
尝试过重启没有效果

LiteLoader版本1.0.3
插件下载的是releases里的1.0.0版本

**Comment by xtaw** [comment]
音频文件大概多大

**Comment by xtaw** [comment]
音频文件大小多大

**Comment by File-saver** [comment]
650KB

**Comment by xtaw** [comment]
.silk文件有大小吗

**Comment by File-saver** [comment]
80KB

**Comment by xtaw** [comment]
是否有安装LLAPI插件

**Comment by File-saver** [comment]
前面没装，以为是liteloader里的，但是现在装完后还是不太行，发出的音频是嘈杂声

**Comment by File-saver** [comment]
110s的音频是5秒，30s的音频是1秒

**Comment by xtaw** [comment]
不是太嘈杂的话是正常的，silk格式是有损压缩，音质会差一点

**Comment by xtaw** [comment]
语音时间不对？

**Comment by File-saver** [comment]
是，而且只听得到嘈杂声

**Comment by xtaw** [comment]
有试过其他音频文件吗

**Comment by File-saver** [comment]
试过，也不行

**Comment by File-saver** [comment]
中途生成的.pcm用ffplay和vlc都播放不了

**Comment by File-saver** [comment]
而且生成速度特别快，30多MB的文件也是秒生成.pcm，感觉出了问题，生成.silk是慢一点

**Comment by xtaw** [comment]
.pcm文件生成快正常，也确实播放不了，应该是生成.silk的时候有问题

**Comment by xtaw** [comment]
LLAPI版本降级到1.3.1.1即可

**Comment by FishCMD** [comment]
感谢，现在llapi升级到1.4.0也可以了

**Comment by Zorrok-k** [comment]
我和你一样的情况，但我甚至没看到pcm文件生成
