### ISSUE TITLE
试了下，会发出纯噪声，原因未知

### ISSUE THREAD

**Issue by djkcyl** [xtaw/LiteLoaderQQNT-Audio-Sender#8]
发送的是 svp 渲染的wav文件

[1_MixDown.zip](https://github.com/xtaw/LiteLoaderQQNT-Audio-Sender/files/14298198/1_MixDown.zip)

直接在qq里听语音条是一段十几秒的噪声

**Comment by xtaw** [comment]
我这边正常发送，试试1.0.1版本，加了点异常处理，应该会比较好找出来问题

**Comment by klxf** [comment]
> 我这边正常发送，试试1.0.1版本，加了点异常处理，应该会比较好找出来问题

1.0.1 依然存在这个问题，只有一行日志
```
[!Renderer:Log:2] sendElements [{type: ptt, file: C:\Users\*\Downloads\test.wav.silk}]
```

**Comment by xtaw** [comment]
LLAPI版本多少

**Comment by klxf** [comment]
> LLAPI版本多少

LLAPI 1.3.1.2
ffmpeg 2.8.4
silk_codec 0.0.6

**Comment by xtaw** [comment]
问题找到了，LLAPI版本降级到1.3.1.1即可，他的最新版好像自带了一个silk转化，但是现在还有点bug
